spring:
  profiles:
    active: dev
    # 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
  jpa:
    properties:
      hibernate: 
        show_sql: true         # 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
        format_sql: true       # SQL문을 가독성 있게 표현
        use_sql_comments: true # 디버깅 정보 출력

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern:  '%h %l %u %t "%r" %s %bbyte %Dms'
    basedir: applog/mqttIngestor

logging:
  config: classpath:logback-spring.xml
  file:
    name : log/mqtt-app.log
    max-history : 30
#    path: applog/mqttIngestor
    max-size: 30MB
    
management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  profiles: old-dev
  datasource:
    url: jdbc:mysql://175.106.98.100:3306/shop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Skcnc123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
  data:
    mongodb:  
      uri: mongodb://admin:admin@175.106.98.100:27017/mqtt

logging:
  level:
    root: DEBUG
mqtt:
  url: tcp://175.106.98.100:1883
  clientid: skyangmqtt001
  
  
---
spring:
  profiles: new-dev
  datasource:
    url: jdbc:mysql://101.79.10.245:3306/shop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Skcnc123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
  data:
    mongodb:  
      uri: mongodb://admin:admin@101.79.10.243:27017/mqtt

logging:
  level:
    root: DEBUG
mqtt:
  url: tcp://175.106.98.100:1883
  clientid: skyangmqtt001
  
---
spring:
  profiles: old-opr
  datasource:
    url: jdbc:mysql://10.0.200.6:3306/shop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Skcnc123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
  data:
    mongodb:  
      uri: mongodb://admin:admin@10.0.200.6:27017/mqtt  

logging:
  level:
    root: DEBUG
mqtt:
  url: tcp://10.0.200.6:1883
  clientid: skyangmqtt001

---
spring:
  profiles: new-opr
  datasource:
    url: jdbc:mysql://10.0.110.12:3306/shop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Skcnc123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
  data:
    mongodb:  
      uri: mongodb://admin:admin@10.0.110.11:27017/mqtt

logging:
  level:
    root: DEBUG
mqtt:
  url: tcp://10.0.200.6:1883
  clientid: skyangmqtt001
