spring:
  profiles:
    active: dev
    # 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
  jpa:
    properties:
      hibernate: 
        show_sql: true         # 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
        format_sql: true       # SQL문을 가독성 있게 표현
        use_sql_comments: true # 디버깅 정보 출력

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern:  '%h %l %u %t "%r" %s %bbyte %Dms'
    basedir: applog/mqttIngestor

logging:
  config: classpath:logback-spring.xml
  file:
    name : log/mqtt-app.log
    max-history : 30
#    path: applog/mqttIngestor
    max-size: 30MB
    
management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://175.106.98.100:3306/shop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC 
    username: root
    password: Skcnc123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
logging:
  level:
    root: INFO
mqtt:
  url: tcp://175.106.98.100:1883
  clientid: testclient
---
spring:
  profiles: stg
  datasource:
    url: jdbc:mysql://localhost:3306/DB명작성?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC 
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    root: DEBUG
mqtt:
  url: tcp://175.106.98.100:1883
---
spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://localhost:3306/DB명작성?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC 
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    # mysql 사용 
    database: mysql 
    # 콘솔에 sql 출력 여부  
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    root: ERROR
mqtt:
  url: tcp://175.106.98.100:1883

